services:
  discovery-service:
    build:
      context: .
      args:
        SERVICE_PATH: :module-infra:discovery-service
        JAR_PATH: module-infra/discovery-service
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  user-service:
    build:
      context: .
      args:
        SERVICE_PATH: :module-api:user-service
        JAR_PATH: module-api/user-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/roomhub?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: roomuser
      SPRING_DATASOURCE_PASSWORD: roompass
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EUREKA_URL: http://discovery-service:8761/eureka/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      discovery-service:
        condition: service_started

  gateway-service:
    build:
      context: .
      args:
        SERVICE_PATH: :module-infra:gateway-service
        JAR_PATH: module-infra/gateway-service
    ports:
      - "8000:8000"
    environment:
      EUREKA_URL: http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_started

  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roomhub
      MYSQL_USER: roomuser
      MYSQL_PASSWORD: roompass
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      retries: 10
      timeout: 3s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
