services:
  discovery-service:
    build:
      context: .
      args:
        SERVICE_PATH: :module-infra:discovery-service
        JAR_PATH: module-infra/discovery-service
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  user-service:
    build:
      context: .
      args:
        SERVICE_PATH: :module-api:user-service
        JAR_PATH: module-api/user-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/couchping
      SPRING_DATASOURCE_USERNAME: couchuser
      SPRING_DATASOURCE_PASSWORD: couchpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EUREKA_URL: http://discovery-service:8761/eureka/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      discovery-service:
        condition: service_started

  reservation-service:
    build:
      context: .
      args:
        SERVICE_PATH: :module-api:reservation-service
        JAR_PATH: module-api/reservation-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/couchping
      SPRING_DATASOURCE_USERNAME: couchuser
      SPRING_DATASOURCE_PASSWORD: couchpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EUREKA_URL: http://discovery-service:8761/eureka/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      discovery-service:
        condition: service_started

  gateway-service:
    build:
      context: .
      args:
        SERVICE_PATH: :module-infra:gateway-service
        JAR_PATH: module-infra/gateway-service
    ports:
      - "8000:8000"
    environment:
      EUREKA_URL: http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_started

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: couchping
      POSTGRES_USER: couchuser
      POSTGRES_PASSWORD: couchpass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U couchuser -d couchping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
